### PR TITLE
performance: use Array instead of Collection

### PR DESCRIPTION
**Pull request by WilianZilv**

### CODE REVIEW

**Comment by Nick-vanGemeren** [comment]
What performance improvements do you expect for small and very large JSON arrays? Note that every time you call ReDim Preserve the entire array is copied to a new array.

There are some backward-compatibility issues:

- Collections have first element (1). Arrays have first element (0). This could be fixed in the ReDim statement.
- Existing code may be using the Count/Add/Remove methods which are not available for Arrays. 
- Existing code may be using Typename/Vartype methods to navigate (and verify) the data structure.

So your ParseArray should be available as a non-default compilation option.

Note that no maintenance is being done on this repo. Don't hold your breath for the PR.

**Comment by WilianZilv** [comment]
> What performance improvements do you expect for small and very large JSON arrays? Note that every time you call ReDim Preserve the entire array is copied to a new array.
> 
> There are some backward-compatibility issues:
> 
> * Collections have first element (1). Arrays have first element (0). This could be fixed in the ReDim statement.
> * Existing code may be using the Count/Add/Remove methods which are not available for Arrays.
> * Existing code may be using Typename/Vartype methods to navigate (and verify) the data structure.
> 
> So your ParseArray should be available as a non-default compilation option.
> 
> Note that no maintenance is being done on this repo. Don't hold your breath for the PR.

Actually, i forgot to explain what i mean by performance.
I dont think the change by itself benefits the parser.

I did this change because i'm using json to write data in the sheet, to do that i need to convert the Collection to an array, which is too slow (i was testing with 100k values), with Collections it can take 1+ minutes, with arrays the conversion to the structure i need is much less expensive, resulting in less than a second to do so.

**Comment by dornech** [comment]
Cool stuff, I struggled with the limit of 256 elements in a VBA collection and was working on replacing it by array. GLad i found it here.
However, one idea: If you use "Option base 1" and adjust the code slighltly, I think it is more compatible with the original Collection approach

**Comment by dornech** [comment]
unfortunately it seems to be a problem to parse an JSON top-level array?

**Comment by Nick-vanGemeren** [comment]
There may have been a limit of 256 in early VBAs but no-one has reported hitting a Collection count limit recently. As above, people are processing very large JSON Arrays. VBA isn't necessarily the best option for simple processing of massive data sets.

**Comment by dornech** [comment]
Well, might be an issue resolved in other versions of VBA - but nevertheless it depends on the source data retrieved. and i would nor call 256 entities in a list an amount of data one would not handle with VBA ...

 

I tried to use an own collection class wrapping an array with an collection interface and was almost successfull. 

 

However, before finally fixing I found https://github.com/omegastripes/VBA-JSON-parser which suffices my need except the index struture i e the list start with element 0 than 1. Another option not yet tried is https://github.com/mlocati/vba-json/blob/main/Json.bas. I started with Tim's VBA-JSON because it seemed something like a de facto standard but at least omegastripe's solution seems to be not bad either with a more or less drop-in user interface.

While Tim's approach seems to be the oldest one, the others seem to be more compact and better maintained.

 

 
 

Gesendet: Montag, 23. September 2024 um 01:36 Uhr
Von: "Nick van Gemeren" ***@***.***>
An: "VBA-tools/VBA-JSON" ***@***.***>
Cc: "dornech" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [VBA-tools/VBA-JSON] performance: use Array instead of Collection (PR #255)


 

There may have been a limit of 256 in early VBAs but no-one has reported hitting a Collection count limit recently. As above, people are processing very large JSON Arrays. VBA isn't necessarily the best option for simple processing of massive data sets.

**Pull request closed without merging**
